version: '2'
services:
  proxy_pool:
    build: .
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      db_type: REDIS
      db_host: proxy_redis
      db_port: 6379
  proxy_redis:
    image: "redis"
