version: '2'
services:
  proxy_pool:
    build: .
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      db_type: REDIS
      db_host: proxy_redis
      db_port: 6379
    networks:
      - backend
    depends_on:
      - proxy_redis
  proxy_redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
