[tox]
envlist = py38,py39,py310,py311
skip_missing_interpreters = true

[testenv]
deps =
    six
    requests
    pyquery
    gunicorn
    lxml
    redis
    APScheduler==3.2.0;python_version<"3.10"
    APScheduler==3.10.0;python_version>="3.10"
    click==8.0.1
    Flask==2.1.1
    werkzeug==2.1.0
commands = python test.py